### ISSUE TITLE
Les "caractères non pris en charges" font partie des commentaires

### ISSUE THREAD

**Issue by xvw** [kdisneur/brainfuck#1]
Salut, à la vue de ton code : 

```haskell
c   -> (i, ((Left (errorMessage c i)):instructions))
```

J'ai l'impression que si tu as "un caractère non pris en charge", il renvoie une erreur :'( 
Normalement, il doit être ignoré. 

(Ou alors peut être que je n'ai rien compris :D)

**Comment by kdisneur** [comment]
Effectivement, j'avais pas vu cette règle. C'est encore plus simple en fait
